# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/ejercicios',
                'doc_host': 'https://nex.github.io',
                'git_url': 'https://github.com/nex/ejercicios',
                'lib_path': 'ejercicios'},
  'syms': {'ejercicios.core': {'ejercicios.core.foo': ('core.html#foo', 'ejercicios/core.py')}}}
